### ISSUE TITLE
如何设置参考文献的页数

### ISSUE THREAD

**Issue by VitalC-3026** [Tr0py/NKU-thesis-template-2020#10]
如何设置参考文献中的页码，比如1-6页，使用的是短横线，而不是波浪线？我使用的是overleaf上的模板。

**Comment by Tr0py** [comment]
你的意思是现在的页码是`1-6`而你想要`1~6`？如果不是你能描述一下问题和你想要的结果吗？

**Comment by VitalC-3026** [comment]
你好，是我的页码现在是1~6，我想要1-6。谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月25日(周三) 凌晨5:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tr0py/NKU-thesis-template-2020] 如何设置参考文献的页数 (Issue #10)




 
你的意思是现在的页码是1-6而你想要1~6？如果不是你能描述一下问题和你想要的结果吗？

**Comment by Tr0py** [comment]
注释掉`references.tex`中的`\def\bibrangedash{ $\sim$ }`这一行就可以。 这一行是在设置页码的分隔符，$\sim$就是波浪线。默认是`-`。所以你注释掉这一行就可以了。同理，你可以设置其他的分隔符。

**Comment by Tr0py** [comment]
如图<img width="1187" alt="image" src="https://user-images.githubusercontent.com/37894237/170152047-447f3ffa-08b0-4a3e-a76e-6ec6955347db.png">

**Comment by VitalC-3026** [comment]
感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月25日(周三) 上午8:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tr0py/NKU-thesis-template-2020] 如何设置参考文献的页数 (Issue #10)




 
注释掉references.tex中的\def\bibrangedash{ $\sim$ }这一行就可以。 这一行是在设置页码的分隔符，$\sim$就是波浪线。默认是-。所以你注释掉这一行就可以了。同理，你可以设置其他的分隔符。
