### ISSUE TITLE
数学环境修改字体

### ISSUE THREAD

**Issue by Ginnn77** [Tr0py/NKU-thesis-template-2020#2]
你好，我想讲数学环境的字体格式改成 \theoremstyle{definition}
但一直显示报错，查了下，可能和某个宏包有冲突，想问下该如何解决，十分感谢！

**Comment by Ginnn77** [comment]
问题已解决[https://tex.stackexchange.com/questions/514584/theoremstyle-causing-error-undefined-control-sequence-and-missing-begindoc?newreg=dda8ff3ca8b943d8bfb72fc0cc4119db](url)

**Comment by Tr0py** [comment]
感谢分享
