### ISSUE TITLE
模板中的标题格式与指导手册不一致

### ISSUE THREAD

**Issue by aqni** [Tr0py/NKU-thesis-template-2020#24]
模板中正文数字标题格式（参见[NKThesis.sty的105至107行](https://github.com/Tr0py/NKU-thesis-template-2020/blob/3c7c61721dbecf36f04124c6b649a6fa4934a221/NKThesis.sty#LL105C1-L107C104)）与指导手册（参见[通知](http://jwc.nankai.edu.cn/2022/1124/c24a497818/page.htm)的附件1）中不符。

此外，我看了一下往年的格式要求，好像一直没变化，前几届没有遇到格式不合格的问题吗？

模板格式：
```tex
\def\chaptername{第\texorpdfstring{\CJKnumber{\arabic{chapter}}}{\arabic{chapter}}章}
\def\thesection{第\texorpdfstring{\CJKnumber{\arabic{section}}}{\arabic{section}}节}
\def\thesubsection{{\texorpdfstring{\enghei}{}\arabic{chapter}.\arabic{section}.\arabic{subsection}}}
```

指导手册格式要求
> 3.标题格式。毕业论文（设计）正文数字标题书写顺序依次为：一、（一）1. (1) ①；第一级标题用小三号黑体字，第二级标题用四号黑体字，第三级及以下标题用小四号黑体字。

**Comment by Tr0py** [comment]
每个学院会有不同的要求。我记得当年这是计算机相关学院的要求。现在各个学院之间可能也会有不同。你们是哪个学院？

另外，这是个好issue，如果模板可以有对于不同学院的格式支持会更好。

**Comment by aqni** [comment]
这个是学校教务处发布的，也是今年计算机学期早前通知中的要求，参见http://jwc.nankai.edu.cn/2022/1124/c24a497818/page.htm

**Comment by aqni** [comment]
据我了解，周政和药学院的格式要求基本和学校教务处的格式一致。我推测现在各学院都基本遵照了学校教务处的要求。

**Comment by Tr0py** [comment]
这么看来，学校可能在尝试统一毕业论文格式要求。

这看起来是件好事！终于有比较一致的格式要求可以参考了。我之后有空应该会按照教务处格式修改一下模板。谢谢你的信息！

如果你想提交PR或者来维护这个模板也很欢迎！

**Comment by aqni** [comment]
目前，我针对教务处要求重新编写了latex格式代码，但是代码架构与当前代码有较大差别，当前模板是否允许大规模重构？

主要区别：
1. 只使用了latex2e语法，当前模板大规模使用plain tex语法；
2. 无页眉；
3. 基于ctexart而非book。

当前代码应该比较古老了，如果允许大规模重构的话，我建议开一个新分支进行过渡；如果没有必要进行大规模重构，我计划最近花一些时间对当前模板进行修补。

**Comment by Tr0py** [comment]
我看了你的代码，非常干净整洁！我很喜欢。

关于是否要重构当前代码（我假设是重构成你的模板的架构），我能想到的要考虑的问题是：
1. 有哪些是当前代码能提供，但是latex2e+ctexart提供不了的吗？
    a.  当前代码提供了的功能还需要被保留吗？（比如英文支持和硕博模板支持，此仓库需要提供吗？）
    b. 你现在的代码有什么已知的limitation吗？
2. 如果只靠我们俩的话，我们俩有能力实现大规模重构吗？（我现在一周大概只有2小时左右的时间可以用来做这个项目。）

我现在还没有仔细思考这件事情。你有什么理解吗？我个人是更偏向于能够有一套更clean的代码的。

> 为了避免加剧各模板各自为战的现状，我还是希望将工作集中在当前仓库。

Good point!

**Comment by aqni** [comment]
### 功能支持

首先，现在硕博论文和本科论文两者格式可以共用的部分很少，在同一个模板中实现并不能减少工作量。其次，对硕博论文功能的支持其实集成自原硕博论文模板，而[原硕博论文模板](https://github.com/NewFuture/NKThesis)尚在维护，我认为没有必要做重复工作。我不知道使用英文写作本科毕业论文的人多不多，而且教务处也没有给出英文论文的格式要求，我认为这个可以搁置。

下面我尝试列出可能受限的功能，分别进行讨论：

1. 非xetex引擎的支持。如果基于ctex系列宏包编写中文模板，将非常困难。
3. 数学环境。我不太熟悉，但是应该只需要调用宏包，或许可以参考其他学长编写的模板。
4. 目录。想要完全重新实现当前模板的目录格式比较困难，好在教务处格式对目录格式的限制较少。
5. 附录。教务处格式要求不明确，有多种可能。我针对字面意思以及周政的附录要求也进行了适配。
6. 浮动体编号。如果在附录中使用按章节编号的图表，编号会变得奇怪，需要进行更多条件判断，好在教务处格式允许统一编号。
7. 行距。实现word中的1.5倍行距是latex中老生常谈的问题，我也没啥好办法，目前通过`linepread`实现，大致一样。
8. 参考文献。目前我直接使用gbt7714-2015，可能不符合要求，但是可以把当前模板中的参考文献格式进行保留。
9. 图注。我其实不懂教务处格式中的图注啥意思，应该和题注不是一个意思，没啥实现思路。

### 架构选择

其他优秀模板（如[THU](https://github.com/tuna/thuthesis)、[FDU](https://github.com/stone-zeng/fduthesis)、[USTC](https://github.com/ustctug/ustcthesis)）往往大而全，如果模板编写者不提供相关选项，使用者很难对模板进行调整。而我校各学院或多或少会有自己的差异化要求，恰恰需要模板能够方便的进行局部调整。

我认为应当选择小而精的架构，只提供最小功能实现，同时应当调用主流宏包，方便后来者维护。所以、数学环境、伪代码环境、算法环境这种特定专业的，没有在教务处格式中体现的要求，不应当在模板类文件中实现，而应当通过示例说明相关宏包的使用方法，由使用者自行调用。

为了解决学院间格式有差异的问题，我建议的一种模板架构如下
```bash
nkuthesis-ug.cls #只实现教务处格式
├── cs.sty       #计算机学院样式补丁与常用宏包配置
├── xxx.sty      #其他学院样式补丁与常用宏包配置
……
```

这里有一篇“[LaTeX-模板开发最佳实践](https://github.com/ustctug/ustcthesis/wiki/LaTeX-模板开发最佳实践)”我认为很有参考价值。

### 工作量

如果仅实现本科毕业论文中文模板，重构的工作量并不大。原因有二：

- 当前模板中的大部分使用 plain tex 实现的功能，在主流宏包中均已实现（这也是我说当前模板古老的原因），而且具有良好的兼容性。例如：
  - 题注：`caption`
  - 字体、标题、标点处理：`ctex`
  - 目录：`titletoc`
  - 页边距（包括页眉页脚的边距）：`geometry`
  - 列表格式：`enumerate`
- 本科毕业论文的格式要求比较简略，远远没有硕士论文详细，需要调整的内容较少，大部分保留ctex默认即可。

当前两三个星期我比较空闲，这段时间我每周应该可以花十几个小时修改模板，但是本科毕业后我可能没有精力继续参与模板的维护。

此外，如果将我已经实现的部分直接复制过来，其实几乎不需要实现其他内容。

**Comment by Tr0py** [comment]
### 功能支持

如果我没理解错的话，你的意思是此模板目前只需要支持中文本科格式，以后可以根据需求考虑支持英文。我觉得有道理。

关于功能支持可能面临的问题，我主要担心的是目录，其他的听起来问题不大：
1.  目录。我没太懂难以实现的“当前模板的目录格式”是指哪些？是说`第x章`, `第x节` 这样对于目录的自定义吗？还是正文与摘要目录所使用的数字体系的区分？比如正文使用阿拉伯数字，其他使用罗马数字。
2. 引擎支持的话只有xelatex我觉得问题不大，因为无论是在overleaf还是本地编译，xelatex都很容易配置。有任何情况需要用非xelatex的特定编译器来编译吗？
3. 数学环境应该也没问题。根据之前数院使用模板反馈的问题来看，多数都是宏包能够解决的。
4. 编号，行距，听起来问题不大。
5. 图注的话应该是使用者自己实现的。用subfigure应该就可以实现。
6. 你说的错误处理是什么意思？

这么看来，如果能够解决目录的问题的话，我们只在xelatex下支持中文本科模板听起来功能性上影响不大。

### 架构选择

同意。看起来如果采用这个架构的话，会非常整洁。但是我们得提供好帮助文档来方便使用者修改模板的细节，比如字体字号，封面的“系别”“学院”的顺序调整，以及添加新的封面内容等。因为每年，即便是今年，也有人来问这些问题。

### 工作量

所以这么看来我们可能是需要保留当前模板的目录和参考文献格式，其他内容可以使用你的代码吗？此外还需要写一些帮助文档。除了简单介绍新版本的参数和格式调整方法外，还有一个常见问题解答，可以参考群里之前的聊天记录。

所以要做的事情就是：
1. 将你的代码复制到此模板来。
2. 把此模板的被你的代码取代的代码清理掉。
3. 确保目录（如果保留当前模板目录的话）和参考文献正常工作，你的代码正常工作。
4. 写一点帮助文档。
5. 更新到overleaf。

我可以把你加到此模板的collaborator中。这样你可以比较方便地开新的分支以及merge。我觉得在确保新模板正常工作前，我们可以先保留当前master分支不变，在dev分支和dev-xxx分支中开发和merge。

你怎么觉得？

**Comment by Tr0py** [comment]
为了统一开发环境，我加了docker compile。这样我们可以都用texlive 2022来进行编译，与overleaf编译器版本保持一致。

直接调用`make docker-compile` 就可以。

**Comment by aqni** [comment]
这两天我就开始着手进行。看起来写文档是最主要的部分。

**Comment by Tr0py** [comment]
那也可以。如果方便的话最好可以把与教务处格式要求有区别的实现列出来，留作以后todo。

我已经向你发了collaborator邀请。https://github.com/Tr0py/NKU-thesis-template-2020/invitations
