### ISSUE TITLE
根据新要求，修正参考文献格式

### ISSUE THREAD

**Issue by aqni** [Tr0py/NKU-thesis-template-2020#31]
相关要求：

> 参考文献应根据各学科正式发表学术论文的规范要求书写，并按在论文中引用的顺序进行排列。每篇文献最多列出3位作者，超出3位时，中文写“等”，英文写“et al”(斜体)。作者的姓名一律姓在前名在后，欧美人的名字可以用缩写字母，且缩写名后省略缩写点“.” 。参考文献应另起一页，一律放在正文后。
>
> 《中国高校自然科学学报编排规范》中几种主要参考文献著录表的格式为：
> 连续出版物：作者.文题.刊名，年，卷号（期号）：起\~止页码。
> 专（译）著：作者.书名（译音）.出版地：出版者，出版年，起\~止页码。
> 论文集： 作者.文题.见（In）：编者,编（eds.）文集名.出版地：出版者，出版	年，起\~止页码。
> 学位论文：作者.文题:[博士或硕士学位论文].授予单位，授予年。
> 专利：申请者.专利名.国家.专利文献种类.专利号，授权日期。
> 技术标准：发布单位.技术标准代号.技术标准名称.出版地:出版者，出版日期。
> 人文社会科学论文的文献资料格式为：
> 图书：著者.书名.出版者，出版时间，版次，页次。
> 期刊：作者.篇名.期刊名称，期号。
> 报纸：作者.篇名.报纸名称，日期，版次。
>
> 举例如下：
> 参考文献
> [1] 庞青山.论大学学科组织及其特色.高等理科教育，2005，63（5）：1\~3.
> [2] Koh Y W, Lai C S, Loh K, et al. Growth of bismuth sulfide mamowire using bismuth trisxanthate single sourcepre- cursors. Chem Mater, 2003, 15(24): 4544 \~4554. 
> [3] 李明.物理学.北京：科学出版社，1977，58\~62.
> [4] Dupont B. Bone marrow transplantation in severe combined immunodeficiency with an unrelated MLC compatible donor. In：White H J, Smith R, eds. Proceedings of the Third Annual Meeting of the International Society for Experimental Hematology. Houston：International Society for Experimental Hematology, 1974.44\~46．
> [5] 胡刚.蛋白质深度分析以及基因的进化模型：[博士学位论文].天津:南开大学，2005.
> [6] 姚光起.一种氧气镐材料的制备方法.中国专利.ZL891056088，1980-07-03.
> [7] 中华人民共和国国家技术监督局.GB3100-3102.中华人民共和国国家标准.北京：中国标准出版社，1994-11-01.
>
> 以上序号用中扩号，与文字之间空两格。如果需要两行的，第二行文字要位于序号的后边，与第一行文字对齐。中文用五号宋体，外文用五号Times New Roman字体。

从字面意思上理解，《中国高校自然科学学报编排规范》并不是唯一标准，具体依据是 **“各学科正式发表学术论文的规范”**，似乎需要根据需要随时添加所需样式。

暂时保留如下两种样式：
- 原计算机学院样式的实现
- 现有GB7714-2015的调用

**Comment by aqni** [comment]
### 考虑移除原计算机学院样式的实现

据我观察原计算机学院样式的实现 fork 自 Casper Ti. Vector。不知道当前仓库内的cbx和bbx在原始Casper Ti. Vector作何修改？

若bbx无修改修改，可以移除 nkthesis.bbx 转而直接使用 biblatex-caspervector 样式。同时使用 biblatex 宏包选项代替单独的nkthesis.cbx文件。

**Comment by aqni** [comment]
是否合并PR有待商榷

**Comment by Tr0py** [comment]
> ### 考虑移除原计算机学院样式的实现
> 据我观察原计算机学院样式的实现 fork 自 Casper Ti. Vector。不知道当前仓库内的cbx和bbx在原始Casper Ti. Vector作何修改？
> 
> 若bbx无修改修改，可以移除 nkthesis.bbx 转而直接使用 biblatex-caspervector 样式。同时使用 biblatex 宏包选项代替单独的nkthesis.cbx文件。

我merge觉得问题不大。因为符合新版本要求就可以，删掉这些文件让仓库更整洁蛮好的。
