### ISSUE TITLE
调整代码架构，适应多模板需求

### ISSUE THREAD

**Issue by aqni** [Tr0py/NKU-thesis-template-2020#50]
尝试整合硕博模板，并行程序课程设计模板。

同时考虑各学院对格式的差异化需求。

> 这项工作放在下一个大版本发布后再考虑着手。

**Comment by aqni** [comment]
这里是重要观点的大纲描述
- 面向模板开发者和模板使用者不是同一套代码
  - 开发者编写dtx源码和示例tex文档
  - 模板使用者使用cls文档，模板手册，tex示例文档。

**Comment by Tr0py** [comment]
> 尝试整合硕博模板，并行程序课程设计模板。

并行程序课程设计模板是指王老师教的那节并行课的模板？

> 每套模板单独打包。

是说release的时候单独打包，但是放在一个仓库里面的意思吗。

如果兼容三个模板，他们共享了哪些文件？

**Comment by aqni** [comment]
> 并行程序课程设计模板是指王老师教的那节并行课的模板？

### 为什么要兼容并行课的模板？

是王老师那节课，那节课可能计算机学院不少同学的latex启蒙课，也能对模板起到宣传作用。

> 是说release的时候单独打包，但是放在一个仓库里面的意思吗。

是的，可以通过构建系统实现自动打包，make和l3build都可以

> 如果兼容三个模板，他们共享了哪些文件？

### 为什么要兼容硕博模板？

现在流行的硕博模板维护在 https://github.com/NewFuture/NKThesis 。但是根据作者描述：
 https://github.com/NewFuture/NKThesis/issues/19#issuecomment-1066026355 。作者似乎已经不自己进行维护了。

### 并行课的模板

并行课的模板其实没有标准，一般使用助教根据个人喜好提供的模板，只要美观即可，暂不考虑同异。

### 硕博模板

如果兼容硕博模板，就是以久经考验的 https://github.com/NewFuture/NKThesis 中的实现结果基准，但是代码架构不兼容。

近似点（微调即可重用）：
1. 共享用户手册
2. 页眉
3. 摘要
4. 参考文献
5. 附录
6. 目录
7. 致谢
8. 图表格式（主要是题注）
9. 页码

不适合重用：
1. 标题格式
2. 封面
3. 声明
4. 图和附表清单、符号、标志、缩略语等的注释表
5. 简历
6. 页边距
7. 公式
8. 双面打印
9. 勘误页

格式未定义：
1. 脚注

总之，硕博论文的格式要求除去与本科论文冲突的部分，比本科论文要求更详细，是本科论文的超集。

### 工作量

相当于重写一个硕博论文模板，目前可能无法完成，就当先挖个坑吧

**Comment by Tr0py** [comment]
> 那节课可能计算机学院不少同学的latex启蒙课，也能对模板起到宣传作用。

有道理。这样其实也可以让我们把模板放到NKUICS的并行课相关板块，帮助宣传。

> 目前主要是希望从顶层设计上满足同时维护多模板的需要，方便后续扩展其他模板。

可以！

ok，我觉得你说的很合理。那就是先调整架构保证代码对其他模板的兼容性，然后自然应该可以支持并行课模板因为并行课没有明确格式要求所以可以直接用本科生模板的格式，最后是硕博模板作为未来的工作，对吧？

**Comment by aqni** [comment]
这两天我整个pr出来
