### ISSUE TITLE
增加计网学院本科毕业论文格式

### ISSUE THREAD

**Issue by aqni** [Tr0py/NKU-thesis-template-2020#52]
昨天学院通过指导老师分发了格式规范。计网版与教务处版差异较大，与硕博版更像，可以作为实现硕博版的过渡。同时正好实践一下用一套源码维护多个模板。事发突然，措手不及。

**Comment by hiroki-chen** [comment]
更新版的模板已经初步制作出来了，张莹和刘彦平老师以此为依据发了新版的 latex 参考模板，格式上与新版指导手册基本一致（*可能*还需要校对）。如果需要的话我可以开一个 PR 过来。
@Tr0py @aqni 觉得如何？

**Comment by aqni** [comment]
可能你有所不知，代码最近重构了。

而且我们希望当前仓库需要同时维护各学院不同的模板。

**Comment by aqni** [comment]
(16)关于刊物的卷期
(A)正常：年, [空格]卷(期):起-止页码
(B)如果无期号，则为：年, [空格]卷:起-止页码
(C)如果有期号无卷号，则为：年, [空格](期):起-止页码
(D)不能出现 vol, no, pp 等字样。

**Comment by aqni** [comment]
格式要求汇总
---

### 结构

- 封面、目录、摘要和关键词、英文摘要和关键词，各个章节，参考文献，致谢等另启一页；

### 封面

起始的“南开大学”为 56 号宋体加粗，字之间有一个空格；下面空一行，该
行字体为宋体，小五；“本科生毕业论文（设计）”为二号宋体。

中英文题目按如下要求：
- 中文楷体加粗，三号，左对齐
- 英文Times New Roman 每个实词首字母大写，题目第一个词不是实词首字母也要大写，三号
- 第二行的题目和上一行“：”后的题目处对齐。
- 第二行题目不足一行，应该补齐一行

封面信息：
- 中文是楷体3号，西文 Times New Roman 3号
- 横线与最长的哪一行看齐（院系那一行）
- 左对齐
- 年级写全，不能是 06 级
- 日期写 ××××年×月即可
- 指导教师要写上职称。如果有多个教师，应该每个一行，且南开大学的教师在第一行。形式如下
```
××× 教授
××× 教授（**大学） 
```

### 章节标题
- 第一章 题目 (word 标题 1 格式，居中，三号黑体) 
  - 第一节 题目 (word 标题 2 格式，居中，小三号黑体) 
    - 1.1.1 题目 (word 标题 3 格式，左边顶格对齐，四号黑体) 

章、节标题居中。第 3 级标题左对齐 

每一章从新的一页开始，不能强制从奇数页开始——也就是说，不能出现完全没有内容的空白页（只有页码，页眉也算空白页）。例子，如果第一章结束于第 5 页，第二章应该从第 6 页开始，不能强制加一个空白页作为第 6 页（使得第二章从奇数的第 7 页开始），该页却没有实质内容

### 页眉页脚

页眉为本章题目（或摘要等），居中，页眉下面应该有横线（正常都有）。

下面页脚为页号，正文格式“1”、“2”样式，Times New Roman 字体，小五
大小，居中，正文前的摘要等格式为“I”，“II”样式。

封皮不能出现页眉页脚，封皮页眉处也不能出现单独的一行横线

### 项目编号

小节中经常出现需要分 1，2，3 等编号项目的内容，建议参照如下分级顺序
给出，可以不按照下面分级顺序给出，但是全文应该统一。
1. 一级【注意：“(”和“)”为英文括号，首字和编号离开一个英文空格】
(1) 二级【注意：“(”和“)”为英文括号，首字和编号离开一个英文空
格】
(A) 三级【注意：“(”和“)”为英文括号，首字和编号离开一个英
文空格】
(B) 三级【注意：“(”和“)”为英文括号，首字和编号离开一个英
文空格】
(C) 三级【注意：“(”和“)”为英文括号，首字和编号离开一个英
文空格】
(2) 二级【注意：“(”和“)”为英文括号，首字和编号离开一个英文空
格】
(3) 二级【注意：“(”和“)”为英文括号，首字和编号离开一个英文空
格】
2. 一级【注意：“(”和“)”为英文括号，首字和编号离开一个英文空格】
3. 一级【注意：“(”和“)”为英文括号，首字和编号离开一个英文空格】
4. 一级【注意：“(”和“)”为英文括号，首字和编号离开一个英文空格】
注意：
(1) 根据文章需要，各项目符号缩进不一定同上面那样。
(2) 如果有特殊必要（如，文章的该小节较长）可在 1,2，3 上面再增加
一层更高级的编号，(一), (二), (三) 【注意：“(”和“)”为英文
- 7 - 
第二章 文章基本格式要求
括号，首字和编号离开一个英文空格】。
(3) 必要时，某些部分可以加粗，或者使用较大一号的字体。

### 中文摘要

建议400字以内，但是不宜太短，建议大于 250 字。

1. 摘要中不可出现引用、图片、图表、表格或其他插图材料。
2. 摘要应该用第三人称的角度去写，如“该文”，“文章”，“论文”等，不
要出现“我们”、“本文”等字样。
3. 若出现英文缩写，首次出现应该给出汉语全称和英文全称，如：万维网
（World Wide Web, WWW）， 第二次出现则可以直接使用缩写。一些实
在没有办法给出中文意思的缩写可以直接给出缩写。
4. 英文缩写和汉语全称如果不确定，需要通过百度，Google 等工具上网查
询。
5. “摘要”格式见“本科生毕业论文（设计）指导手册”。

### 关键词

一般 4～7 个

中文要求：
1. 是“关键词”，不能写成“关键字”。
2. 用中文分号分开。
3. 中文关键词，不能出现纯英文形式的关键词。如果要出现英文缩写，
应先给出中文全称，再用括号给出缩写，括号应该为西文括号，不能
仅仅给出缩写。
4. 最后一个关键词后面没有任何如“.”，“。”的符号。
5. 如果关键词一行放不开，第二行要和上一行的“：”后对齐

英文要求：
1. 注意是“Key Words”，不是“Key Word”，“ Key words”，“ Keywords”等(不是别的不对，统一为“Key Words”)。
2. 用西文“;”加“1 个西文空格” 分开，最后一个不写。（西文分号占位较小，后面需要增加一个空格）
3. 除了一些特殊关键词，各个单词首字母都不要大写
4. 如果要出现英文缩写，应先给出英文全程称，再用括号给出缩写，括号应该为西文括号，括号前有一个西文空格。

### 目录

1. 目录两个字要居中。
2. 页码前后的“-”可以不要。
3. 目录应该包括“摘要”，“Abstract”，“目录”。
4. 一级标题（章）字体为小三号宋体。
5. 二级标题（节）字体为四号宋体。
6. 三级标题（1.1.1, 1.1.2, ……）字体为小四号宋体。

### 标点

除非特别需要，文章中的正文部分内容应该都是中文的标点符号

### 缩略语表

如果论文中使用了大量的物理量符号、标志、缩略词、专门计量单位、自定
义名词和术语等，应编写成注释说明汇集表(单独作为文章的一部分，“缩略语
表”)。若上述符号使用数量不多，可以不设此部分，但必须在论文中出现时加
以说明

1. “缩略语表”可放在参考文献之后作为附录出现，也可以放在，
目录之后、第一章之前。
2. 按照英文缩写排序。
3. 下面的附表 1 为一个例子（注：该编号由于是要体现附表，故编
号为附表 1）

### 缩略语

第一次出现某个英文缩写，应该给出汉语全称和英文全称（即使摘要中已经
给了全称和缩写

### 文献引用

1. 引用采用形如“[1]”的形式，其中中括号为西文中括号。
2. 引用以上标形式给出。
3. 参考文献顺序按照引用顺序出现。
4. 章节标题上不能出现引用，该条一定要注意。
5. 引用中若出现“,” 则应采用西文符号，如果有必要可在逗号后加空格。
6. 引用中若出现 “－”则应采西文减号“-”。

其它形式引用
1. 两个同时，[1,5]，数字从小到大。
2. 多个连续，[7-10]。
3. 多个非连续，[6,9,11,29] ，数字从小到大。
4. 其它情况，[4-8, 19]，[3-6, 20, 41-43]。

### 正文中英文符号和公式

大部分句子中出现的英文符号，除了单位等一般要斜体编排，并采用“Time New Roman”字体。

如果文中出现公式，而且正文中出现公式中出现的变量，一般要把变量用公式键入，或者采用西文字体并且斜体，以和公式中一致。文字、公式混派的地方，公式和文字的中心应该在一条线上，不要出现公式、文字高矮错落、字体大小不一致等情况造成最终排版很不美观情况。

### 公式排版

1. 公式全文编号要一致，要求按照各章分别从 1 开始连续编号，基本编号格式为(1.1)，(1.2)，…，(2.1)，(2.2)，…，(3.1)，(3.2)，…  注意：
  a. 公式中的“.”为西文点，且点前的 1，2 等表示章。
  b. 括号都是西文括号“（”和“）”。
  c. 必要时可出现特殊的编号如(1.A)，(3.A)等，但是这些都是极少数，一般做为文章核心公式，经常被引用。这样的公式中的点和括号都是英文，点前为章号。
  d. 使用 MathType 可以自动生成满足需要的公式编号。
  e. 使用 Latex 编写论文可以公式自动得到满足需要的公式编号。
2. 编号不允许再细分为 1.1.1, 1.1.2 等三级形式。
3. 编号不允许全文从 1 开始连续编号。
4. 公式的编号括号右对齐，公式主体部分全文居中。【注:可以右对齐，然后插入“Tab”或者空格使公式居中。】
5. 无编号公式也要居中。
6. 某些证明过程中的公式可以不编号。一个公式一行写不下，可以分为几行，一般新的一行以“+”，“－”，“=”等运算符号开始，在“=”/“≤”/“≥”/“<”/“>”处对齐。
7. 如果公式后有标点符号应该都是英文的“,”和“.”。
5. 全文公式排版要格式一致
  a. 向量一般为列向量，不要有些章节为列向量，有些章节为行向量。
  b. 矩阵记号要一致，要么全文用[]，要么全文用()。对于向量的记号要求
  也是一样。
  c. 矩阵和向量符号标识要全文一致，如：
    (i) 全文用一致的 I 或 E 表示单位矩阵
    (ii) 矩阵都采用大写字母或者大写希腊字母表示
    (iii) 向量都采用小写字母或者小写希腊字母表示

### 定义、定理、引理等

1. 定义、定理、引理等分别分章从 1 开始连续编号，如定义 1.1，定理 1.1，
定义 2.1，定理 2.2 等，点用西文点，点前表示章。
2. 定义、定理、引理这些字加粗，定义、定理、引理的中文字体应为楷体，
这样排版美观。

### 图

文中引用别人的图都应该给出参考文献的引用。要求：
1. 图题应该在图的下面，五号字体居中，表达要清晰，最后没有标点符号。
2. 图编号同定义等编号，按照章节，以“图 1.1”，“图 1.2”或者“图 1-1”，“图1-2”形式给出。
3. 图的编号后面加一个空格之后再写图的内容。
4. 文中的图都要有名称，而且任何两个不允许重名。
5. 图本身要清晰。
6. 图要清晰，居中放置，各个坐标轴要有标识。如：图如果有横纵坐标，就一定要有坐标轴单位，单位的位置要全图美观。如，都在坐标轴的居中位置，都在坐标轴原理原点的那一边，而且离开原点位置比例要相等。
7. 如果一个图有多个子图，应该各个子图应该给予(a) (b) (c) (d)等编号，对于子图的说明可以放在图题中说明，也可以分别在(a) (b) (c) (d)后说明。
8. 图和图题不能分开，要放在一页内。
9. 子图(a)(b)等标识（含可能的说明）应该在各个子图下方正中间。
10. 若一个图中有多条曲线，一定要在图中用插入的子图或者图的名称处说明各
个曲线的含义。有些图需要重做，保证在黑白打印机上打印出来能分清楚。
11. 图单独编号，不能与表格混编。

### 表格

文中引用别人的表都应该给出参考文献的引用。
1. 要居中，表名称在上面，表头字体应该为 5 号。
2. 表名称要有意义，但不能太长，一般不要超过 2 行，表头要和表在一页上。如果表格太长，可以分两页，第二页上的表格要写上续表××。
3. 一般表格内的字体要比正文的字体小，毕业论文表格为 5 号字体。
4. 表格左对齐，或者居中对齐, 一般情况下小数位数应该一致。
5. 表头要给出单位，单位要用国际通用标准单位，如 m, km，s，cm，ml，
不要用个别地区所用单位，如：市斤，市尺等。
6. 一般表格单独编号，不要与图混编。每一章分别连续编号，点为西文点，
点前表示章，例如
表 1.1，表 1.2，…，表 2.1，表 2.2，… 
7. 表格边框格式不做要求，但是全文要一致。
8. 表格都要有名称，全文任何两个表格名称不许相同。

### 程序

一般，文章不允许大量出现代码，但是有时也需要出现一些代码。对于这些
代码，要求：
1. 这些字体应该比正文字体要小，比如大部分内容为小四号字体，那么
程序代码应该采用五号字体。
2. 程序行间距应该为单倍间距（全文可能是 1.5 倍间距或者 1.2 倍间距）。
3. 程序部分底色应该为白色。
4. 程序部分上下应该和正文分开，推荐用“——————”分开。

### 参考文献格式

一般本科生论文参考文献 20～50 篇。一般中英文文献都应该有，中文文
献应该超过 5 篇，外文文献应该超过 5 篇。

在引文处按论文中引用文献出现的先后用阿拉伯数字连续编序，将序
号置于方括号内，并视具体情况把序号作为上角标，或作为语句的组
成部分。如：“…… 张×× [1] 、王×× [2,3] 和李××等 [4-6] 对这一现象作
了研究，数学模型见文献［7］。”
(2) 参考文献前面序号格式为“[1]”，“[2]”，…，中括号为西文中括号。
如果换行，下一行要有所缩进，并于上一行文献主体内容对齐，如：
(3) 每篇文献最多列出3位作者，超出3位时，中文写“等”，英文写“et 
al”(斜体)。
(4) 参考文献字体：宋体 10.5 磅（五号）（英文用 Times New Roman 体
五 号），行距 16 磅，段前段后 0 磅。
(5) 所有出现在参考文献中的标点符号都是西文标点符号“,”，“:”，“.”。
(6) 每一条参考文献最后没有任何标点符号。
(7) 期刊文章和会议文章可以加上 [J], [C]等表示，但是[博士学位论文]，
[硕士学位论文]需要加上。
(8) 几种主要参考文献著录表的格式为：【注意：空格用[空格]表示】
(9) 关于起~止页码：统一采用“-”，注意：
(A)全文的“-”者要一致，不能同时出现出现各种不同的连字符“-”/
“－”/“—”。
(B)某些刊物的没有起-止页码，只有论文代号，这种情况仅给出代号。
(10)关于书籍：一定要有出版地，如：“北京:清华大学出版社”。
(11)关于网络文献，由于网址较长，有时需要自己在合适的“/”前面手动
加上一个空格才能获得较好的格式，并且论文中不要有太多网络文献。
注意：不能仅仅给出一个网络地址，要从这个地址里找出该
文献的作者（可能是一个组织或团体），文献名称
12. 关于论文名称：要求第一个单词首字母大小，其余都小写(除了一些专
有名称、缩写等)，
13. 关于刊物/会议名称：
(A)论文要求给出刊物或者会议的全称，方便别人查阅。刊物缩写与全
称对照可查看文件《西文杂志名缩写对照表》和《ISI 期刊名称缩
写与全称对照表》。这是一个复杂的格式订正过程，各个学生严格执
行。
(B)全称的英文刊物/会议名称：实词首字母都要大写，例如
关于中文作者：
(A)作者之间用西文逗号＋空格分开。
(B)超过三个作者用也要全部给出来。
注：需要找到原来的文献，把作者等补全。
(C)最后加上西文句号和空格。
关于西文作者，和中国作者拼音
(A)多个作者中间用西文逗号＋空格分开，超过三个作者用也要补全作
者，最后加西文句号和空格。
(B)作者之间不能出现“and”。
(C)中文拼音按照“姓[空格]中间字头[空格]最后一个字字头”，如：“Li C H”，
“Li T”，“Liu Z X”，“Zhang S S”。
(D)他国作者也是按照类似方式先给 Family name / Sir name / First 
name，如：“Torvik P J”，“ Grigorenko I”，“Tricaud C”，“Agiza 
H N”，“Rosenstein M T”。
(E)一些特殊字母（非英文国家作者名称）在拷贝时可能会被丢弃，需
要自己订正，如 Nedić.可以通过插入符号实现，如图 4.1 所示
(16)关于刊物的卷期
(A)正常：年, [空格]卷(期):起-止页码
(B)如果无期号，则为：年, [空格]卷:起-止页码
(C)如果有期号无卷号，则为：年, [空格](期):起-止页码
(D)不能出现 vol, no, pp 等字样。

**Comment by hiroki-chen** [comment]
> 可能你有所不知，代码最近重构了。
> 
> 而且我们希望当前仓库需要同时维护各学院不同的模板。
> 
> @hiroki-chen
> 
> 不过我觉得可以先直接合并到主分支，主分支还没有重构

了解，那我们先提交一个初步的 PR 吧，之后重构完成可以尝试加入，不行的话可以做一个备份啥的

**Comment by Tr0py** [comment]
计网版的要求是你发的这些吗？：https://github.com/Tr0py/NKU-thesis-template-2020/issues/52#issuecomment-1567752065

让我理解下，计院在答辩结束后发布了格式要求？这是今年的毕业论文格式要求？然后让毕业生临时改下格式交上去的意思？

**Comment by aqni** [comment]
格式是答辩结束才发布的。不过上面的要求我已经按照根据重构后的代码进行了修改，除了列表样式已经都实现完成了，等后面多模板架构完成我就添加进来。

**Comment by aqni** [comment]
是今年的要求，我转述了一下，不知道原来的文件能不能公开，反正没有网站链接，我也在wiki上传一份原稿。
