### ISSUE TITLE
Undefined control sequence. \NKT

### ISSUE THREAD

**Issue by BlueWhale0-0** [Tr0py/NKU-thesis-template-2020#59]
![1710468724817](https://github.com/Tr0py/NKU-thesis-template-2020/assets/53010149/a564b67f-9084-4e5a-ad6c-267b81c302de)
![1710469571618](https://github.com/Tr0py/NKU-thesis-template-2020/assets/53010149/4b240b1e-f814-4efe-8c81-e44cc9836c5f)
编译毕业论文在overleaf和texstudio分别出现上述报错，导出的PDF文件导航栏中章节标题变为  “第1零章XXX、第2零章XXXX”
请问如何解决上述问题呢？

**Comment by Tr0py** [comment]
请分享一下用来复现问题的代码和流程。

overleaf编译是宋体没有找到的问题，检查一下宋体字体文件在不在，有没有被正确命名为 `SumSun` .

textstudio需要你的tex来复现问题。看起来你的main.tex第一行有语法错误。

**Comment by Tr0py** [comment]
问题有被解决吗？
