### ISSUE TITLE
行距不统一，如何调整？

### ISSUE THREAD

**Issue by Ginnn77** [Tr0py/NKU-thesis-template-2020#6]
发现定理环境和证明环境的间距不统一，请问，该如何调整？
![image](https://user-images.githubusercontent.com/78025214/115543574-1c824d00-a2d4-11eb-8d70-43a166828d10.png)
<img width="507" alt="image" src="https://user-images.githubusercontent.com/78025214/115543758-55222680-a2d4-11eb-8ae2-f0c89c3fc778.png">

<img width="662" alt="image" src="https://user-images.githubusercontent.com/78025214/115543817-62d7ac00-a2d4-11eb-8892-816a6d27b36a.png">

**Comment by Tr0py** [comment]
请发上来你的间距不一致的latex源代码，让我复现问题。

**Comment by Ginnn77** [comment]
> **可能的解决方法**: 你可以尝试`\vspace{-1em}`这样的操作。
> 请发上来你的间距不一致的latex源代码，让我复现问题。

感谢，利用`\vspace`解决了。
