### ISSUE TITLE
overleaf上字数统计功能报错

### ISSUE THREAD

**Issue by AlyssaChen2003** [Tr0py/NKU-thesis-template-2020#60]
<img width="1071" alt="82f0eda41c61c0a54b1ffc9a1f097af" src="https://github.com/Tr0py/NKU-thesis-template-2020/assets/115961511/c5e8fee1-f2ea-4b55-a665-93f353933cee">

**Comment by Tr0py** [comment]
你的文件目录结构是什么样子的？（overleaf左侧目录树）

**Comment by AlyssaChen2003** [comment]
就是原始的模板的目录，没改动过
![image](https://github.com/Tr0py/NKU-thesis-template-2020/assets/115961511/d4206c68-b7cf-46a7-9b04-2d09e459b9b1)

**Comment by Tr0py** [comment]
overleaf的字数统计只有在 `main.tex` 处于根目录的时候才会正常工作。你的所有 tex 文件都处于 `thesis` 目录下。把thesis目录下的东西都移到根目录下，删掉 `thesis` 目录，应该就可以了。 一个正常的目录如图所示：

![image](https://github.com/Tr0py/NKU-thesis-template-2020/assets/37894237/04231b0e-ece2-4b6d-bac0-1e06f35da77c)


正常的字数统计：

![image](https://github.com/Tr0py/NKU-thesis-template-2020/assets/37894237/21c3b4f8-3a35-449b-a5ea-4d26f4e484b3)



reference: https://tex.stackexchange.com/questions/577523/why-is-overleaf-unable-to-locate-my-file-sections-in-the-path-im-trying-to-get

**Comment by AlyssaChen2003** [comment]
okok，解决了，谢谢学长or学姐
