### ISSUE TITLE
NKThesis.sty 定义重复

### ISSUE THREAD

**Issue by VitalC-3026** [Tr0py/NKU-thesis-template-2020#9]
在NKThesis.sty的第40行\csname xeCJK@enc@UTF8\endcsname，显示xeCJK@enc@UTF8已经被定义过了。请问这个应该怎么调整呢？

**Comment by VitalC-3026** [comment]
解决方法：把NKThesis.sty的34行注释掉

**Comment by Tr0py** [comment]
我没懂，为什么要这样修改呢？  是想要新feature吗？还是这是一个需要修复的bug？

**Comment by VitalC-3026** [comment]
想修复一个bug。因为放到overleaf上面会报错：NKThesis.sty第40行\csname xeCJK@enc@UTF8\endcsname，显示xeCJK@enc@UTF8已经被定义过

**Comment by Tr0py** [comment]
什么叫“放到overleaf上面会报错”？在overleaf上的模板我看到的是没有错误的，你说的“放到overleaf”上是指你自己import的还是overleaf的模板有错？

**Comment by VitalC-3026** [comment]
我发现点击overleaf链接后使用的模板没有问题。我把这个仓库的压缩包下载下来，再上传到overleaf上，就会出现我之前的报错。

**Comment by Tr0py** [comment]
hmmm..有趣。我的猜测是你新建的project用的默认编译器不一样导致的报错。如果模板本身的配置没问题那我就当没bug要改了。 谢谢分享。:)

**Comment by zdx100** [comment]
问题解决了吗？我也遇到类似问题，一直无法解决。注释一些内容后，参考文献部分无法正常显示。我是换了台电脑，原来的电脑能正常运行，新电脑报错，很奇怪。

**Comment by Tr0py** [comment]
报错信息是什么？如何复现你的问题？

**Comment by Tr0py** [comment]
我似乎见过这个问题。这个似乎是因为新版本的XeLaTeX编译器包含了`\CJKaddEncHook`的定义，导致定义重复。你尝试用早一点版本的编译器试试。比如XeLaTeX 2019就可以解决这个问题。

你在overleaf上的话，可以直接在setting里面选择编译器版本。你如果自己编译的话，用docker image可以快速切换编译器版本。

**Comment by Tr0py** [comment]
我记得我有个commit fix了这个问题：https://github.com/Tr0py/NKU-thesis-template-2020/commit/a1eb382830750a5151bdb06fd11056d5921ff582

你试试。

**Comment by ChristinaGZH** [comment]
> 我记得我有个commit fix了这个问题：[a1eb382](https://github.com/Tr0py/NKU-thesis-template-2020/commit/a1eb382830750a5151bdb06fd11056d5921ff582)
> 
> 你试试。

感谢大佬，我差点都要卸载重装texlive啦
